<?php

return [
    'namespace' => 'Modules',

    'paths' => [
        'modules' => base_path('Modules'),
        'assets' => public_path('modules'),
        'migration' => app_path('Database' . DIRECTORY_SEPARATOR . 'migrations'),
        'generator' => [
            'config' => ['path' => 'Config'],
            'command' => ['path' => 'Console'],
            'migration' => ['path' => 'Database' . DIRECTORY_SEPARATOR . 'migrations', 'generate' => true],
            'factory' => ['path' => 'Database' . DIRECTORY_SEPARATOR . 'factories'],
            'model' => ['path' => 'Models'],
            'repository' => ['path' => 'Repositories'],
            'seeder' => ['path' => 'Database' . DIRECTORY_SEPARATOR . 'seeders'],
            'controller' => ['path' => 'Http' . DIRECTORY_SEPARATOR . 'Controllers'],
            'filter' => ['path' => 'Http' . DIRECTORY_SEPARATOR . 'Middleware'],
            'request' => ['path' => 'Http' . DIRECTORY_SEPARATOR . 'Requests'],
            'provider' => ['path' => 'Providers'],
            'component' => ['path' => 'View' . DIRECTORY_SEPARATOR . 'Components'],
            'policy' => ['path' => 'Policies'],
            'event' => ['path' => 'Events'],
            'listener' => ['path' => 'Listeners'],
            'routes' => ['path' => 'Routes'],
            'views' => ['path' => 'Resources' . DIRECTORY_SEPARATOR . 'views'],
            'test' => ['path' => 'Tests'],
            'test-unit' => ['path' => 'Tests' . DIRECTORY_SEPARATOR . 'Unit'],
            'test-feature' => ['path' => 'Tests' . DIRECTORY_SEPARATOR . 'Feature'],
            'lang' => ['path' => 'Resources' . DIRECTORY_SEPARATOR . 'lang'],
        ],
    ],

    'commands' => [
        CommandMakeCommand::class,
        ControllerMakeCommand::class,
        DisableCommand::class,
        DumpCommand::class,
        EnableCommand::class,
        EventMakeCommand::class,
        FactoryMakeCommand::class,
        InstallCommand::class,
        JobMakeCommand::class,
        LaravelModulesV6Migrator::class,
        ListCommand::class,
        ListenerMakeCommand::class,
        MailMakeCommand::class,
        MigrationMakeCommand::class,
        ModelMakeCommand::class,
        ModelShowCommand::class,
        ModuleDeleteCommand::class,
        ModuleMakeCommand::class,
        NotificationMakeCommand::class,
        PolicyMakeCommand::class,
        ProviderMakeCommand::class,
        PublishCommand::class,
        PublishConfigurationCommand::class,
        PublishMigrationCommand::class,
        PublishTranslationCommand::class,
        RequestMakeCommand::class,
        ResourceMakeCommand::class,
        RouteProviderMakeCommand::class,
        RuleMakeCommand::class,
        SeedCommand::class,
        SeedMakeCommand::class,
        SetupCommand::class,
        TestMakeCommand::class,
        UpdateCommand::class,
    ],

    'register' => [
        'Pendaftaran',
        'Akademik',
        'Presensi',
        'Keuangan',
        'Nilai',
        'Pegawai',
        'Persuratan',
        'Perpustakaan',
        'Dapur',
        'Kantin',
        'Alumni',
        'Ppdb',
        'Berita',
    ],

    'scan' => [
        'enabled' => false,
        'paths' => [
            base_path('vendor/*/*'),
        ],
    ],

    'composer' => [
        'vendor' => 'simt',
        'author' => [
            'name' => 'SIMT MTs',
            'email' => 'dev@simt-mts.id',
        ],
    ],

    'cache' => [
        'enabled' => env('MODULES_CACHE_ENABLED', false),
        'key' => 'simt-modules',
        'lifetime' => 60,
    ],

    'activator' => 'file',

    'statuses' => [
        'enabled' => true,
        'disabled' => false,
    ],
];
